# Just allow any in/out communication in the "snglr-model-checker" namespace; This is so that we dont deny requests for Keycloak ie. the "authenticate.dev-snglr.com"

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - from: # Allow all that have JWT
    - source:
        requestPrincipals: ["*"]
  - to: # allow all for GET requests
    - operation:
        methods: [GET]
  - to: # Allow all to this host
    - operation:
        hosts: ["health.dev-app.snglr.com"]
  - to: # allow all to path /info...; that have "resource_access" fields in the JWT; and have specific audience
    - operation:
        paths:
          - /info*
    when:
      - key: 'request.auth.claims[resource_access][deleteme4][roles]'
        values:
          - deleteme-role
      - key: request.auth.audiences
        values:
          - snglr-model-checker-web # this is needed because otherwise we will see only audience "account" and that gets denied