apiVersion: v1
kind: Service
metadata:
  name: health
  namespace: deleteme
spec:
  # type: NodePort
  ports:
  - targetPort: 8080
    port: 80
    name: http
  - targetPort: 8080
    port: 8080
    name: http2
  selector:
    app: health



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
  namespace: deleteme
spec:
  selector:
    matchLabels:
      app: health
  replicas: 1
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name: health
        ports:
          - containerPort: 8080
        image: vladmasarik/ser
