apiVersion: v1
kind: Service
metadata:
  name: health
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    name: http
  selector:
    app: health


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
spec:
  selector:
    matchLabels:
      app: health
  replicas: 1
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name: health
        image: vladmasarik/ser

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: health
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  rules:
    - host: health.dev-app.snglr.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: health
              servicePort: 8080